# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title function sin(x)
#' @description function sin(x)
#' @param x the value of the independent variable
#' @return the value of sin(x)
#' @examples
#' \dontrun{
#' sin(2)
#' }
#' @export

fun <- function(x) {
  .Call(`_SA23204184_fun`, x)
}

#' @title calculate the integral of the function
#' @description calculate the integral of the function
#' @param down the value of the lower bound
#' @param up the value of the higher bound
#' @param n the number of intervals divided
#' @return the integral
#' @examples
#' \dontrun{
#'     LeftRect(1,2,100)
#' }
#' @export



LeftRect <- function(down, up, n) {
    .Call(`_SA23204184_LeftRect`, down, up, n)
}

